# Generated by Django 6.0.2 on 2026-04-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
