# Generated by Django 6.0.2 on 2026-05-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_date_joined_user_last_name_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
