# Generated by Django 6.0.2 on 2026-05-23 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_name_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField()),
                ('discount_type', models.PositiveSmallIntegerField(choices=[(1, 'Percent'), (2, 'Amount')], default=2)),
                ('max_discount', models.IntegerField(blank=True, help_text='Only for percentage discounts', null=True)),
                ('min_order_amount', models.IntegerField(default=0)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='userorder',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='core.useraddress'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='categoryproduct',
            table='category_product',
        ),
        migrations.AddField(
            model_name='userorder',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='core.discount'),
        ),
        migrations.CreateModel(
            name='DiscountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discount')),
            ],
            options={
                'db_table': 'discount_categories',
                'unique_together': {('category_id', 'discount_id')},
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='If empty, available for all categories', related_name='categories', through='core.DiscountCategory', to='core.category'),
        ),
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discount')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'discount_products',
                'unique_together': {('product_id', 'discount_id')},
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='If empty, available for all products', related_name='products', through='core.DiscountProduct', to='core.product'),
        ),
        migrations.CreateModel(
            name='DiscountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discount')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discount_users',
                'unique_together': {('user_id', 'discount_id')},
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='If empty, available for all users', related_name='users', through='core.DiscountUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExcludeDiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discount')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'exclude_discount_products',
                'unique_together': {('product_id', 'discount_id')},
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='exclude_products',
            field=models.ManyToManyField(blank=True, help_text='If empty, available for all excluded products', related_name='exclude_products', through='core.ExcludeDiscountProduct', to='core.product'),
        ),
    ]
