# Generated by Django 6.0.2 on 2026-05-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_discount_alter_userorder_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='categories',
        ),
        migrations.AlterUniqueTogether(
            name='discountproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='discountproduct',
            name='discount_id',
        ),
        migrations.RemoveField(
            model_name='discountproduct',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='products',
        ),
        migrations.AlterUniqueTogether(
            name='discountuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='discountuser',
            name='discount_id',
        ),
        migrations.RemoveField(
            model_name='discountuser',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='users',
        ),
        migrations.AlterUniqueTogether(
            name='excludediscountproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='excludediscountproduct',
            name='discount_id',
        ),
        migrations.RemoveField(
            model_name='excludediscountproduct',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='exclude_products',
        ),
        migrations.AddField(
            model_name='userorder',
            name='total_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DiscountCategory',
        ),
        migrations.DeleteModel(
            name='DiscountProduct',
        ),
        migrations.DeleteModel(
            name='DiscountUser',
        ),
        migrations.DeleteModel(
            name='ExcludeDiscountProduct',
        ),
    ]
