# Generated by Django 6.0.2 on 2026-05-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_discount_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='user_order',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='order',
            new_name='user_order',
        ),
        migrations.RenameField(
            model_name='userorder',
            old_name='total_sale',
            new_name='final_amount',
        ),
    ]
