# Generated by Django 6.0.2 on 2026-04-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_providers',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Admin'), (3, 'Accountant')], default=1),
        ),
    ]
