# Generated by Django 6.0.2 on 2026-05-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_order_order_user_order_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='discount',
            table='discount',
        ),
    ]
