# Generated by Django 6.0.2 on 2026-04-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_order_address_remove_order_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='Order',
        ),
    ]
