# Generated by Django 6.0.2 on 2026-05-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_discount_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart',
            new_name='user_cart',
        ),
    ]
