# Generated by Django 6.0.2 on 2026-04-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_order_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='last_name',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='name',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
