# Generated by Django 6.0.2 on 2026-04-28 16:27

import core.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_order_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=core.models.product.image_path),
        ),
    ]
