# Generated by Django 6.0.2 on 2026-04-28 16:52

import core.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=core.models.product.image_path, verbose_name='Image'),
        ),
    ]
