# Generated by Django 6.0.2 on 2026-05-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
