# Generated by Django 6.0.2 on 2026-05-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_userorder_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
