# Generated by Django 6.0.2 on 2026-05-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_payment_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
