# Generated by Django 6.0.2 on 2026-05-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Cancelled'), (2, 'Pending'), (3, 'Returned'), (4, 'Completed'), (5, 'Delivered'), (6, 'Awaiting Payment')], default=6),
        ),
    ]
